%This file generates the plots and numerical performance measures, given the .mat files in the "Results"
%folder generated by "main.m"
%Note that the following code has the plotting of the robust results commented out
%% plot 
load Results/Closed_loop.mat
close all
%
t=0:param.delta:Tsim;
k_nom_infeasible=min(length(t)-1,k_nom_infeasible);
k_soft_infeasible=min(length(t)-1,k_soft_infeasible);

%% PLot
close all
figure(5)
axis([0,7e3/60,0.9,1.5]);  
hold on
plot(t/60,x_relax(1,:),'-b','linewidth',1)
%plot(t/60,x_relax_robust(1,:),'b:','linewidth',1)
plot(t(1:k_soft_infeasible)/60,x_soft(1,1:k_soft_infeasible),'m-.','linewidth',1)
plot(t(1:k_nom_infeasible)/60,x_nom(1,1:k_nom_infeasible),'r--','linewidth',1)
plot([0,t(end)]/60,[1,1]*param.x_max(1),'black:','linewidth',2)
plot(t(k_nom_infeasible)/60,x_nom(1,k_nom_infeasible),'ro','linewidth',2,'markersize',40)
plot(t(k_nom_infeasible)/60,x_nom(1,k_nom_infeasible),'rx','linewidth',2,'markersize',10)
plot(t(k_soft_infeasible)/60,x_soft(1,k_soft_infeasible),'mo','linewidth',2,'markersize',40)
plot(t(k_soft_infeasible)/60,x_soft(1,k_soft_infeasible),'mx','linewidth',2,'markersize',10)
xline(param.disturbances_t(1)/60,'black:','linewidth',1)
xline(param.disturbances_t(2)/60,'black:','linewidth',1)
xline(param.disturbances_t(3)/60,'black:','linewidth',1)
xlabel('time [min]','interpreter','latex','fontsize',15)
ylabel('water level $h_1$ [m]','interpreter','latex','fontsize',15)
legend({'Proposed','Soft','Nominal','Constraint'},'interpreter','latex','location','southeast','fontsize',15)
set(gca, 'fontname','Arial','fontsize',15)
set(gca, 'XTick',[0 30 60])
print('H_1_NoRobust','-depsc')
%% save plot again without x-label
xlabel('')
set(gca, 'XTick',[])
print('H_1_NoRobust_noXlabel','-depsc')
%% PLot
figure(6)
axis([0,7e3/60,0.9,1.55]);  
hold on
plot(t/60,x_relax(2,:),'-b','linewidth',1)
%plot(t/60,x_relax_robust(2,:),'b:','linewidth',1)
plot(t(1:k_soft_infeasible)/60,x_soft(2,1:k_soft_infeasible),'m-.','linewidth',1)
plot(t(1:k_nom_infeasible)/60,x_nom(2,1:k_nom_infeasible),'r--','linewidth',1)
plot([0,t(end)]/60,[1,1]*param.x_max(1),'black:','linewidth',2)
plot(t(k_nom_infeasible)/60,x_nom(2,k_nom_infeasible),'ro','linewidth',2,'markersize',40)
plot(t(k_nom_infeasible)/60,x_nom(2,k_nom_infeasible),'rx','linewidth',2,'markersize',10)
plot(t(k_soft_infeasible)/60,x_soft(2,k_soft_infeasible),'mo','linewidth',2,'markersize',40)
plot(t(k_soft_infeasible)/60,x_soft(2,k_soft_infeasible),'mx','linewidth',2,'markersize',10)
xline(param.disturbances_t(1)/60,'black:','linewidth',1)
xline(param.disturbances_t(2)/60,'black:','linewidth',1)
xline(param.disturbances_t(3)/60,'black:','linewidth',1)
xlabel('time [min]','interpreter','latex','fontsize',15)
ylabel('water level $h_3$ [m]','interpreter','latex','fontsize',15)
%Note that in paper, x(2) is called h_3, since it makes the equations
%shorter to write down; 
%legend({'Proposed','Proposed-robust','Soft','Nominal','Constraint'},'interpreter','latex','location','southeast','fontsize',15)
legend({'Proposed','Soft','Nominal','Constraint'},'interpreter','latex','location','southeast','fontsize',15)
set(gca, 'fontname','Arial','fontsize',15)
set(gca, 'XTick',[0 30 60])
print('H_2_NoRobust','-depsc') 
%% computation time
%evaluate only in interval [0,k_1], where all are feasible 
k_1=50%k_nom_infeasible;

Timing_ms=[round([mean(t_nom(1:k_1))
mean(t_soft(1:k_1))
mean(t_relax(1:k_1))
mean(t_relax_robust(1:k_1))]*1e3,1)';...
round([std(t_nom(1:k_1))
std(t_soft(1:k_1))
std(t_relax(1:k_1))
std(t_relax_robust(1:k_1))]*1e3,1)'];
text={'nominal';'soft';'proposed';'proposed-robust'}';
%Table_ms=table(Timing_ms');
Table_ms=table(text',Timing_ms');
Table_ms.Properties.VariableNames{1}='MPC';
Table_ms.Properties.VariableNames{2}='mean [ms]';
Table_ms.Properties.VariableNames{2}='std [ms]';
display(Table_ms)
%% performance
Performance=[round([
norm(x_nom(1:2,1:k_1)-y_des_close(1:2,1))^2/k_1
norm(x_soft(1:2,1:k_1)-y_des_close(1:2,1))^2/k_1
norm(x_relax(1:2,1:k_1)-y_des_close(1:2,1))^2/k_1
norm(x_relax_robust(1:2,1:k_1)-y_des_close(1:2,1))^2/k_1
],4)'];
%normalize to proposed
Performance=round(Performance/Performance(1),4);
Table_cost=table(text',Performance'*1e2);
Table_cost.Properties.VariableNames{1}='MPC';
Table_cost.Properties.VariableNames{2}='cost [%]';
display(Table_cost)
